Mvc Assignment 3/Models/CheckFever.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc_Assignment_3.Models
{
    public class CheckFever
    {
        public static string Check(double temp, string type)
        {
            string fever = "";

            if (type == "Fahrenheit")
            {
                temp = CheckFahrenheit(temp);
            }
            if (temp >= 38 && temp <= 40)
            {
                fever = "You have a fever!";
            }
            else if (temp > 40)
            {
                fever = "Are you sure you're alive? You're burning up!";
            }
            else if (temp <= 36 && temp >= 34)
            {
                fever = "You have hypothermia!";
            }
            else if (temp < 34)
            {
                fever = "You're practically made of ice! Go seek a doctor!";
            }
            else
            {
                fever = "You do not have fever, hurray!";
            }



            return fever;
        }

        private static double CheckFahrenheit(double temp)
        {
            return (5.0 / 9.0) * (temp - 32);
        }
    }
}

Mvc Assignment 3/Models/GuessCheck.cs
using Mvc_Assignment_3.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc_Assignment_3.Models
{
    public class GuessCheck : IUserGuess
    {
        public List<UserGuess> Guesses = new List<UserGuess>();
        private string idNumber = "Guess nr: ";
        private int idCount = 1;

        private string answer = "";

        public List<UserGuess> AllGuesses()
        {
            return Guesses;
        }

        public UserGuess NewGuess(string details, int guess)
        {
            UserGuess userGuess = new UserGuess() { IdNumber = idNumber, Id = idCount, Details = details, Guess = guess };
            idCount++;
            Guesses.Add(userGuess);
            return userGuess;
        }

        public string Compare(int? userGuess, int RndNumber)
        {
            if (userGuess == RndNumber)
            {
                answer = "Congratulations! You guessed correctly! The number was: ";
            }
            else if (userGuess > RndNumber)
            {
                answer = "Your guess was too big, please try again! Your guess was: ";
            }
            else
            {
                answer = "Your guess was too small, please try again! Your guess was: ";
            }

            return answer;
        }

        public int RandomNumber()
        {
            Random random = new Random();
            //int Number = random.Next(1, 101);
            return random.Next(1,101);
        }

        public List<UserGuess> RemoveAllValues()
        {
            idCount = 1;
            Guesses.Clear();
            return Guesses;
        }
    }
}

Mvc Assignment 3/Models/IUserGuess.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc_Assignment_3.Models
{
    public interface IUserGuess
    {
        UserGuess NewGuess(string details, int Guess);

        List<UserGuess> AllGuesses();

        List<UserGuess> RemoveAllValues();
    }
}

Mvc Assignment 3/Models/UserGuess.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc_Assignment_3.Models
{
    public class UserGuess
    {
        public string IdNumber { get; set; }
        public int Id { get; set; }
        public string Details { get; set; }
        public int Guess { get; set; }
    }
}

Mvc Assignment 3/Controllers/FeverCheckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mvc_Assignment_3.Models;

namespace Mvc_Assignment_3.Controllers
{
    public class FeverCheckController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(double temp, string type)
        {

            ViewBag.Fever = CheckFever.Check(temp, type);

            return View();
        }
    }
}

Mvc Assignment 3/Controllers/GuessingGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Mvc_Assignment_3.Models;

namespace Mvc_Assignment_3.Controllers
{
    public class GuessingGameController : Controller
    {
        public const string SessionKeyUserNumber = "_UserNumber";
        public const string SessionKeyRndNumber = "_RndNumber";
        public const string SessionKeyUserDetails = "_UserDetails";

        GuessCheck guessCheck = new GuessCheck();
        IUserGuess _userGuess;

        public GuessingGameController(IUserGuess userGuess)
        {
            _userGuess = userGuess;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.NewGuess = "Insert a number to keep on guessing!";

            HttpContext.Session.Clear();

            int RndNumber = guessCheck.RandomNumber();

            if (string.IsNullOrEmpty(HttpContext.Session.GetString(SessionKeyRndNumber)))
            {
                HttpContext.Session.SetInt32("_RndNumber", RndNumber);
            }
            return View(_userGuess.AllGuesses());
        }
        [HttpPost]
        public IActionResult Index(int number)
        {
            foreach (var item in _userGuess.AllGuesses())
            {
                if (item.Details.Contains("Congratulations"))
                {
                    _userGuess.RemoveAllValues();
                    break;
                }
            }

            if (number != 0 && "_RndNumber" != null)
            {
                int randomNumber = (int)HttpContext.Session.GetInt32("_RndNumber");
                string details = guessCheck.Compare(number, randomNumber);

                _userGuess.NewGuess(details, number);

                HttpContext.Session.SetInt32("_UserNumber", number);
                HttpContext.Session.SetString("_UserDetails", details);

                if (number == randomNumber)
                {
                    return RedirectToAction("Index", "GuessingGame");
                }
            }
            else
            {
                ViewBag.Blank = "Please enter a value before pressing the button.";
            }
            return View(_userGuess.AllGuesses());
        }
    }
}

Mvc Assignment 3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Mvc_Assignment_3.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Projects()
        {
            return View();
        }
    }
}

Mvc Assignment 3/Views/FeverCheck/Index.cshtml
@{
    ViewData["Title"] = "CheckFever";
}

<h1>FeverCheck</h1>

<form method="post">
    <input name="temp" type="number" placeholder="Fever?" />
    <br />
    <button>Verify if fever or not</button>
    <br />
    <input type="radio" name="type" value="Celsius" checked />Celsius
    <input type="radio" name="type" value="Fahrenheit" />Fahrenheit
</form>

@if (ViewBag.Fever != null)
{
    <h3>Result</h3>
    <p>@ViewBag.Fever</p>
}

Mvc Assignment 3/Views/GuessingGame/Index.cshtml
@model List<UserGuess>
@{
    ViewData["Title"] = "Index";
}

<h1>GuessingGame</h1>

<form method="post">
    <input type="number" name="number" min="1" max="100" value="" placeholder="Guess" />
    <input type="submit" value="Guess" />
</form>

<br />
<br />
<br />

<table id="GuessingGameTable">
    <thead>
        <tr id="testing">
            <td></td>
            <td>Guess</td>
            <td>Description</td>
            <td>Your guess(es)</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.IdNumber</td>
                <td>@item.Id</td>
                <td>@item.Details</td>
                <td>@item.Guess</td>
            </tr>
        }
    </tbody>
</table>

@if (ViewBag.Blank != null)
{
    <p>@ViewBag.Blank</p>
}
@if (ViewBag.NewGuess != null)
{
    <p>@ViewBag.NewGuess</p>
}

Mvc Assignment 3/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h1>About</h1>

<div>
    Here you can get my CV:
    <br />
    <a href="~/Micael Ståhl CV.docx" download>Micael Ståhl CV</a>
</div>

Mvc Assignment 3/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<h1>Contact</h1>

Mvc Assignment 3/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Index";
}

<div>
    This is just me testing to see if I can make it work from Index
</div>

Mvc Assignment 3/Views/Home/Projects.cshtml
@{
    ViewData["Title"] = "Projects";
}

<h1>Projects</h1>

Mvc Assignment 3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/main.css" rel="stylesheet" />
    <script src="~/js/script.js"></script>
</head>
<body onload="StartTimer()">
    <header>
        <nav>
            <!-- Focus on making a nav later. -->
            <a href=""><img src="~/Funny_llama.jpg" alt="Logo" id="logo" /></a>
            <ul class="main-ul">
                <li class="main-li">@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="main-li"><a asp-controller="Home" asp-action="About">About</a></li>
                <li class="main-li"><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                <li class="main-li"><a asp-controller="Home" asp-action="Projects">Projects</a></li>
                <!-- Don't need asp-controller and asp-action on the lower line, but wanted quick access to it -->
                <li class="main-li"><a asp-controller="FeverCheck" asp-action="FeverCheck">FeverCheck</a></li>
                <li class="main-li"><a asp-controller="GuessingGame" asp-action="GuessingGame">GuessingGame</a></li>
            </ul>
        </nav>
    </header>
    <div class="clearfix">
        <div class="main-div">
            @RenderBody()
        </div>
    </div>
    <footer class="navbar fixed-bottom">
        <div id="foot"></div>
    </footer>
</body>
</html>